"""Merged TestCase into Problem

Revision ID: 6c6e2a51cf92
Revises: 4a4c4673468d
Create Date: 2024-09-07 19:22:34.329433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6e2a51cf92'
down_revision = '4a4c4673468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case')
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_cases', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('test_cases')

    op.create_table('test_case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_data', sa.TEXT(), nullable=False),
    sa.Column('expected_output', sa.TEXT(), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
