"""Add Contest, Problem, TestCase, Submission tables

Revision ID: c5880d3e230e
Revises: 6c6e2a51cf92
Create Date: 2024-09-08 14:16:57.980829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5880d3e230e'
down_revision = '6c6e2a51cf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_cases', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('output_cases', sa.Text(), nullable=False))
        batch_op.drop_column('test_cases')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_cases', sa.TEXT(), nullable=False))
        batch_op.drop_column('output_cases')
        batch_op.drop_column('input_cases')

    # ### end Alembic commands ###
